### ISSUE TITLE
1.1.6 release build failed on ArchLinux

### ISSUE THREAD

**Issue by luozhiya** [XmacsLabs/mogan#1114]
### Mogan Version

1.1.6

### Operating System Version and Architecture

Linux R9-7950X-CODE 6.5.5-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 23 Sep 2023 22:55:13 +0000 x86_64 GNU/Linux

### Describe Bug

Command
```
  xrepo update-repo
  xmake config -m release --yes
  xmake build --yes --verbose --diagnosis --jobs=8 --all
```

Output
```
[ 97%]: linking.release mogan
/usr/bin/g++ -o build/linux/x86_64/release/mogan build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o -m64 -L/usr/lib -Lbuild/linux/x86_64/release -Wl,-rpath=$ORIGIN/../lib -Wl,-rpath=$ORIGIN -Wl,-rpath=/usr/lib -s -lmogan -lQt5PrintSupport -lQt5Svg -lQt5Gui -lQt5Widgets -lQt5Core -lpthread
/usr/bin/ld: build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o: in function `immediate_options(int, char**)':
texmacs.cpp:(.text+0x58d4): undefined reference to `get_tm_cache_path()'
/usr/bin/ld: texmacs.cpp:(.text+0x5c40): undefined reference to `get_tm_cache_path()'
/usr/bin/ld: texmacs.cpp:(.text+0x5de8): undefined reference to `get_tm_cache_path()'
/usr/bin/ld: texmacs.cpp:(.text+0x6018): undefined reference to `get_tm_cache_path()'
/usr/bin/ld: texmacs.cpp:(.text+0x6230): undefined reference to `get_tm_cache_path()'
/usr/bin/ld: build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o:texmacs.cpp:(.text+0x62a5): more undefined references to `get_tm_cache_path()' follow
collect2: error: ld returned 1 exit status
error: @programdir/modules/async/runjobs.lua:256: @programdir/actions/build/kinds/binary.lua:74: @programdir/core/sandbox/modules/os.lua:378: execv(/usr/bin/g++ -o build/linux/x86_64/release/mogan build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o -m64 -L/usr/lib -Lbuild/linux/x86_64/release -Wl,-rpath=$ORIGIN/../lib -Wl,-rpath=$ORIGIN -Wl,-rpath=/usr/lib -s -lmogan -lQt5PrintSupport -lQt5Svg -lQt5Gui -lQt5Widgets -lQt5Core -lpthread) failed(1)
stack traceback:
    [C]: in function 'error'
    [@programdir/core/base/os.lua:923]:
    [@programdir/core/sandbox/modules/os.lua:378]: in function 'execv'
    [@programdir/modules/core/tools/gcc.lua:487]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]:
    [@programdir/core/tool/linker.lua:224]: in function 'link'
    [@programdir/actions/build/kinds/binary.lua:74]: in function 'callback'
    [@programdir/modules/core/project/depend.lua:191]: in function 'on_changed'
    [@programdir/actions/build/kinds/binary.lua:55]: in function '_do_link_target'
    [@programdir/actions/build/kinds/binary.lua:105]:
    [@programdir/actions/build/kinds/binary.lua:132]: in function '_link_target'
    [@programdir/actions/build/kinds/binary.lua:160]: in function 'jobfunc'
    [@programdir/modules/async/runjobs.lua:232]:
    [C]: in function 'xpcall'
    [@programdir/core/base/utils.lua:280]: in function 'trycall'
    [@programdir/core/sandbox/modules/try.lua:117]: in function 'try'
    [@programdir/modules/async/runjobs.lua:218]: in function 'cotask'
    [@programdir/core/base/scheduler.lua:404]:

stack traceback:
	[C]: in function 'error'
	@programdir/core/base/os.lua:923: in function 'base/os.raiselevel'
	(...tail calls...)
	@programdir/modules/async/runjobs.lua:256: in field 'catch'
	@programdir/core/sandbox/modules/try.lua:123: in global 'try'
	@programdir/modules/async/runjobs.lua:218: in upvalue 'cotask'
	@programdir/core/base/scheduler.lua:404: in function <@programdir/core/base/scheduler.lua:397>
==> ERROR: A failure occurred in build().
    Aborting...
```

### Expected Behavior

build OK

**Comment by darcy-shen** [comment]
`get_tm_cache_path` is defined in `sys_util.hpp`, just add a patch to add `#include "sys_utils.hpp"` in texmacs.cpp should fix the bug. It seems the linker in archlinux is much more strict.

**Comment by darcy-shen** [comment]
@Charonxin Could you help fix this bug and release v1.1.6.1 for Arch Linux?

**Comment by Charonxin** [comment]
> @Charonxin Could you help fix this bug and release v1.1.6.1 for Arch Linux?

Shall we support ci on arch linux?

**Comment by darcy-shen** [comment]
> Shall we support ci on arch linux?

Yes. You can add CI on branch-1.2.

**Comment by darcy-shen** [comment]
Please help confirm if #1115  fixes the bug. And we can release 1.1.6.1 for ArchLinux.

**Comment by luozhiya** [comment]
With #1115, the linking still has the same error.  IMO,  errors during linking may require modifying the `xmake.lua` script

**Comment by darcy-shen** [comment]
I'm not using ArchLinux. @Charonxin @Oyyko need your help to fix it.

**Comment by luozhiya** [comment]
Using `git bisect `to find the [b6c0f3](https://github.com/XmacsLabs/mogan/commit/b6c0f3d59077fb07cdbce576ae6cc2159461eded) which introduced this build issue.

**Comment by darcy-shen** [comment]
Add `#include "sys_utils.hpp"` to `src/Scheme/Scheme/glue.cpp` should fix it.

**Comment by Oyyko** [comment]
@luozhiya I will work on it. Does it works now?

**Comment by luozhiya** [comment]
@Oyyko
I'm on vacation till 5 October. I won't bring my laptop. See you all soon.

**Comment by Oyyko** [comment]
It runs well on my archlinux, which looks like 
```
                   -`                 
                  .o+`                 zj@zj
                 `ooo/                 OS: Arch Linux 
                `+oooo:                Kernel: x86_64 Linux 6.5.3-arch1-1
               `+oooooo:               Uptime: 3h 29m
               -+oooooo+:              Packages: 1080
             `/:-:++oooo+:             Shell: zsh 5.9
            `/++++/+++++++:            Resolution: 3840x2160
           `/++++++++++++++:           DE: KDE 5.110.0 / Plasma 5.27.8
          `/+++ooooooooooooo/`         WM: KWin
         ./ooosssso++osssssso+`        GTK Theme: Breeze [GTK2/3]
        .oossssso-````/ossssss+`       Icon Theme: breeze
       -osssssso.      :ssssssso.      Disk: 64G / 916G (8%)
      :osssssss/        osssso+++.     CPU: 12th Gen Intel Core i5-12400 @ 12x 4.4GHz [47.0°C]
     /ossssssss/        +ssssooo/-     GPU: Mesa Intel(R) Arc(tm) A770 Graphics (DG2)
   `/ossssso+/:-        -:/+osssso+-   RAM: 3562MiB / 63883MiB
  `+sso+:-`                 `.-/+oso: 
 `++:.                           `-/+/
 .`                                 `/

```

However, I am using xmake dev branch,which looks like
```
xmake v2.8.3+HEAD.2b61611, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io

```

You can update xmake to dev verison by `sudo xmake update --root -s dev` or `xmake update -s dev` (It depends).

**Comment by luozhiya** [comment]
@darcy-shen 
> Add #include "sys_utils.hpp" to src/Scheme/Scheme/glue.cpp should fix it.

The problem still exists.

@Oyyko 

I have tested the latest commit version of xmake and this issue still exists.

`neofetch`
```
                   -`                    yanchcore@R9-7950X-CODE 
                  .o+`                   ----------------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Kernel: 6.5.5-arch1-1 
               `+oooooo:                 Uptime: 1 hour, 8 mins 
               -+oooooo+:                Packages: 1599 (pacman) 
             `/:-:++oooo+:               Shell: bash 5.1.16 
            `/++++/+++++++:              Resolution: 2560x1440 
           `/++++++++++++++:             DE: Xfce 4.18 
          `/+++ooooooooooooo/`           WM: Xfwm4 
         ./ooosssso++osssssso+`          WM Theme: Default 
        .oossssso-````/ossssss+`         Theme: Adwaita-dark [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: elementary [GTK2], Adwaita [GTK3] 
      :osssssss/        osssso+++.       Terminal: xfce4-terminal 
     /ossssssss/        +ssssooo/-       Terminal Font: NotoSansM Nerd Font Mono 13 
   `/ossssso+/:-        -:/+osssso+-     CPU: AMD Ryzen 9 7950X (32) @ 5.881GHz 
  `+sso+:-`                 `.-/+oso:    GPU: AMD ATI 6c:00.0 Raphael 
 `++:.                           `-/+/   Memory: 5093MiB / 112315MiB 
 .`                                 `/

```

`xmake --version`
```
xmake v2.8.3+master.4ea057304, A cross-platform build utility based on Lua
Copyright (C) 2015-present Ruki Wang, tboox.org, xmake.io
                         _
    __  ___ __  __  __ _| | ______
    \ \/ / |  \/  |/ _  | |/ / __ \
     >  <  | \__/ | /_| |   <  ___/
    /_/\_\_|_|  |_|\__ \|_|\_\____|
                         by ruki, xmake.io
    
    👉  Manual: https://xmake.io/#/getting_started
    🙏  Donate: https://xmake.io/#/sponsor

```

**Comment by Oyyko** [comment]
OK. I will check it.

**Comment by Oyyko** [comment]
Still can't reproduce. I guess it's a problem with the xmake version. I'm curious why my xmake information shows `xmake v2.8.3+HEAD.2b61611` and yours shows `xmake v2.8.3+master.4ea057304`. So you are building xmake from the xmake git repo? My way is to install xmake via pacman first, then use `sudo xmake update --root -s dev` to update it. Strange Problem.

**Comment by luozhiya** [comment]
Yes, I am building xmake from the xmake git repo. 

The `debug` version can be successfully compiled. Are you compiling the `release` version?

**Comment by darcy-shen** [comment]
Does the official release of xmake 2.8.3 works?

**Comment by luozhiya** [comment]
@darcy-shen  I have also tested the current stable version [xmake 2.8.3-1](https://archlinux.org/packages/extra/x86_64/xmake) on ArchLinux. The same issue occurred in the compilation of release.

**Comment by darcy-shen** [comment]
@Oyyko From the error message, it should not be a hard issue, could you help fix it using official xmake 2.8.3 installed from archlinux.

**Comment by darcy-shen** [comment]
Arch Linux CI will be enabled in branch-1.2, since @Oyyko  is an Arch Linux user and a Mogan Developer.

**Comment by Oyyko** [comment]
@luozhiya Do you build on the latest commit https://github.com/XmacsLabs/mogan/commit/b3ad400834c99f23b09c2e44cf604947fcdb9a93. Because I am using xmake  v2.8.3 and I am sure that I am building on `release` mode. And it still shows me no errors.

```
[ 96%]: linking.release mogan
/usr/bin/g++ -o build/linux/x86_64/release/mogan build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o -m64 -L/usr/lib -Lbuild/linux/x86_64/release -Wl,-rpath=$ORIGIN/../lib -Wl,-rpath=$ORIGIN -Wl,-rpath=/usr/lib -s -lmogan -lQt5PrintSupport -lQt5Svg -lQt5Gui -lQt5Widgets -lQt5Core -lpthread

build cache stats:
cache directory: build/.build_cache
cache hit rate: 2%
cache hit: 13
cache miss: 452
new cached files: 452
remote cache hit: 0
remote new cached files: 0
preprocess failed: 0
compile fallback count: 0

[100%]: build ok, spent 140.03s
```

**Comment by Oyyko** [comment]
> @luozhiya Do you build on the latest commit [b3ad400](https://github.com/XmacsLabs/mogan/commit/b3ad400834c99f23b09c2e44cf604947fcdb9a93). Because I am using xmake v2.8.3 and I am sure that I am building on `release` mode. And it still shows me no errors.
> 
> ```
> [ 96%]: linking.release mogan
> /usr/bin/g++ -o build/linux/x86_64/release/mogan build/.objs/mogan/linux/x86_64/release/src/Texmacs/Texmacs/texmacs.cpp.o -m64 -L/usr/lib -Lbuild/linux/x86_64/release -Wl,-rpath=$ORIGIN/../lib -Wl,-rpath=$ORIGIN -Wl,-rpath=/usr/lib -s -lmogan -lQt5PrintSupport -lQt5Svg -lQt5Gui -lQt5Widgets -lQt5Core -lpthread
> 
> build cache stats:
> cache directory: build/.build_cache
> cache hit rate: 2%
> cache hit: 13
> cache miss: 452
> new cached files: 452
> remote cache hit: 0
> remote new cached files: 0
> preprocess failed: 0
> compile fallback count: 0
> 
> [100%]: build ok, spent 140.03s
> ```

More info:
```
clang --version                                                                                                            ✔ 
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

```
clang++ -v                                                                                                                 ✔ 
clang version 16.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/13.2.1
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```
```
lua -v                                                                                                                     ✔ 
Lua 5.4.6  Copyright (C) 1994-2023 Lua.org, PUC-Rio
```

```
xmake --version                                                                                                            ✔ 
xmake v2.8.3+20230926, A cross-platform build utility based on Lua
```

**Comment by luozhiya** [comment]
@Oyyko  You're right. 👍 

I have written a [Github Action](https://github.com/luozhiya/arch-mogan/blob/master/.github/workflows/preflight.yml)    to test compiling mogan v1.1.6, and from the [compilation results](https://github.com/luozhiya/arch-mogan/actions/runs/6446786504/job/17502360662) , there is no problem.

Therefore, it may be that some part of my local system has affected the compilation results.

**Comment by luozhiya** [comment]
@hammerfunctor

See https://aur.archlinux.org/packages/mogan#comment-937346

This issue seems to be easy to reproduce on computers that have previously compiled Mogan, but it is not present in the new environment.

Is the caching mechanism of xmake affecting the compilation results？

**Comment by darcy-shen** [comment]
I guess it is because you are linking against the installed mogan 1.1.5.

**Comment by darcy-shen** [comment]
Here is a related issue: https://github.com/XmacsLabs/mogan/issues/531

Remove the installed 1.1.5 and then build and install 1.1.6 should fix the issue.

**Comment by hammerfunctor** [comment]
> Remove the installed 1.1.5 and then build and install 1.1.6 should fix the issue.

Confirmed to be a workaround.

**Comment by Oyyko** [comment]
should we close this issue?

**Comment by darcy-shen** [comment]
Duplicated with #531
